#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-4 -d  1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          20 #12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding  20
bspc config pointer_motion_interval 40
bspc config top_monocle_padding -20
bspc config pointer_motion_interval 6

~/.config/polybar/launch.sh &

xrandr --output DP-4 --primary --mode 3440x1440 --rate 165.00
feh --bg-fill ~/images/wallpapers/nekotokanojo.jpg

picom --config ~/.config/picom/picom.conf & 

dunst & 

# uim-xim &
# uim-toolbar-gtk3 &

python3 ~/.config/xob/pulseAudioWatcher.py | xob &
